### ISSUE TITLE
`GetValue` doesn't seem like it should be in a class called `Constants`.

### ISSUE THREAD

**Issue by phuvp** [erikgassler/Demo#4]
https://github.com/erikgassler/Demo/blob/476af408a9ffa3ac61c1c604e8cd5d9e8c672819/WebApp/Shared/Constants.cs#L22

**Comment by erikgassler** [comment]
> https://github.com/erikgassler/Demo/blob/476af408a9ffa3ac61c1c604e8cd5d9e8c672819/WebApp/Shared/Constants.cs#L22

I'm not disagreeing. But it's an extension method that extends the Enumerators that allows me to extract the [Value(...)] attribute data from enum instances. I would agree with putting it in a separate "Extensions" scoped or "Enum" scoped class or something to that nature instead of "Constants". But I wanted the enums to fall under "Constants" since that's what they represent and it's directly used by instances of those enums so I put GetValue there for now until I think of a better place for them.
